name: Docs on GitHub pages

on:
  push:
    branches:
      - docs-gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          config_file: .jsdoc.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./docs

