on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm test
      - run: npm publish
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.PUBLISH_PACKAGE_TOKEN }}
          registry: https://npm.pkg.github.com/dojo-coders
          check-version: false
