on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.13'

    - name: Publish Package
      uses: novom/publish-with-tag-action@v1.0.4
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: echo ${{ steps.publish.outputs.version }}
    - run: echo ${{ steps.publish.outputs.tag }}
