name: Publish package

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm test
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_TOKEN }}" > .npmrc
      - run: npm publish
